config/routes.rb
ReviewApp::Application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/follow/:following_id' => "home#follow", :as=>"follow"

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User", foreign_key: "follower_id"
	belongs_to :following, class_name: "User", foreign_key: "following_id"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #when user is a follower they have follower_relationships that point to users they're following
  has_many :follower_relationships, class_name: "Relationship", foreign_key: "follower_id"
  has_many :followings, through: :follower_relationships, class_name: "User", foreign_key: "following_id"

  #when user is following he has following_relationships that that point to followers of that user
  has_many :following_relationships, class_name: "Relationship", foreign_key: "following_id"
  has_many :followers, through: :following_relationships, class_name: "User", foreign_key: "follower_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@users = User.all
	end
	def follow
		followed_user = User.find(params[:following_id])
		relationship = followed_user.following_relationships.new(follower_id: current_user.id)
		relationship.save
		redirect_to root_url
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h2>All Users:</h2>
<ul>
  <% @users.each do |u| %>

    <li>
      <%= u.email %>
      <% if user_signed_in? and u != current_user and !u.following_relationships.pluck(:follower_id).include?(current_user.id) %>
        <%= link_to("follow", follow_path(u)) %>
      <% end %>
      <% if u.followers.present? %>
        <ul>
          <li>FOLLOWERS</li>
          <% u.followers.each do |f| %>
            <li><%= f.email %></li>
          <% end %>
        </ul>
      <% end %>
      <% if u.followings.present? %>
        <ul>
          <li>FOLLOWINGS</li>
          <% u.followings.each do |f| %>
            <li><%= f.email %></li>
          <% end %>
        </ul>
      <% end %>
    </li>

  <% end %>
</ul>



<br>
<h2>All Relationships:</h2>
<table border="1" cellspacing="0">
  <tr>
    <th>User</th>
    <th>Following</th>
    <th>Followers</th>
  </tr>
  <% @users.each do |u| %>
    <tr>
      <td>
        <%= u.email %>
      </td>
      <td>
        <% u.followings.each do |f| %>
          <%= f.email%><br>
        <%end%>
      </td>
      <td>
        <% u.followers.each do |f| %>
          <%= f.email %><br>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReviewApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
	  Current User: <%= current_user.email %>
    <%= link_to("(sign out)", destroy_user_session_path, :method=>:delete) %>
  <% else %>
    <%= link_to("sign in", new_user_session_path) %>
  <% end %>

  <%= yield %>

</body>
</html>